"""Utility modules for HWP2HWPX conversion."""

from hwp2hwpx.util.binary import (
    get_bit,
    get_bits,
    read_bytes,
    read_float32,
    read_float64,
    read_hwpunit,
    read_hwpunit16,
    read_int16,
    read_int32,
    read_int64,
    read_shwpunit,
    read_uint8,
    read_uint16,
    read_uint32,
    read_uint64,
    read_wchar_string,
    read_wchar_string_with_length,
    to_unsigned,
)
from hwp2hwpx.util.color import (
    NONE_COLOR_VALUE,
    Color4Byte,
    color_to_hex,
    color_to_hex_with_none_check,
    hwp_color_to_string,
    parse_color_string,
)
from hwp2hwpx.util.compression import (
    compress_stream,
    decompress_stream,
    decompress_stream_safe,
    is_ccl_document,
    is_certificate_drm,
    is_certificate_encryption,
    is_compressed,
    is_distribution_document,
    is_document_history_saved,
    is_drm_secured,
    is_encrypted,
    is_script_saved,
    is_sign_certificate_saved,
    is_sign_information_saved,
    is_xml_template,
)

__all__ = [
    # binary
    "get_bit",
    "get_bits",
    "read_bytes",
    "read_float32",
    "read_float64",
    "read_hwpunit",
    "read_hwpunit16",
    "read_int16",
    "read_int32",
    "read_int64",
    "read_shwpunit",
    "read_uint8",
    "read_uint16",
    "read_uint32",
    "read_uint64",
    "read_wchar_string",
    "read_wchar_string_with_length",
    "to_unsigned",
    # color
    "NONE_COLOR_VALUE",
    "Color4Byte",
    "color_to_hex",
    "color_to_hex_with_none_check",
    "hwp_color_to_string",
    "parse_color_string",
    # compression
    "compress_stream",
    "decompress_stream",
    "decompress_stream_safe",
    "is_ccl_document",
    "is_certificate_drm",
    "is_certificate_encryption",
    "is_compressed",
    "is_distribution_document",
    "is_document_history_saved",
    "is_drm_secured",
    "is_encrypted",
    "is_script_saved",
    "is_sign_certificate_saved",
    "is_sign_information_saved",
    "is_xml_template",
]
