"""HWPX file model."""

from dataclasses import dataclass, field
from typing import Dict, List, Optional


@dataclass
class VersionXML:
    """HWPX version information."""

    version: str = "1.4"
    app_name: str = "HWP Document"
    app_version: str = "10.0.0.0"


@dataclass
class ContainerXML:
    """Container XML (META-INF/container.xml)."""

    root_file_path: str = "Contents/content.hpf"
    root_file_media_type: str = "application/hwpml-package+xml"


@dataclass
class ManifestItem:
    """Single item in manifest."""

    href: str
    media_type: str
    id: str = ""


@dataclass
class ManifestXML:
    """Manifest XML (META-INF/manifest.xml)."""

    items: List[ManifestItem] = field(default_factory=list)

    def add_item(self, href: str, media_type: str, item_id: str = "") -> None:
        """Add item to manifest."""
        self.items.append(ManifestItem(href=href, media_type=media_type, id=item_id))


@dataclass
class SpineItem:
    """Single item in content spine."""

    idref: str


@dataclass
class ContentHPF:
    """Content HPF file (Contents/content.hpf)."""

    # Metadata
    title: str = ""
    language: str = "ko"
    description: str = ""
    creator: str = ""
    date: str = ""

    # Manifest items
    manifest: List[ManifestItem] = field(default_factory=list)

    # Spine (reading order)
    spine: List[SpineItem] = field(default_factory=list)

    def add_manifest_item(self, item_id: str, href: str, media_type: str) -> None:
        """Add item to manifest."""
        self.manifest.append(ManifestItem(id=item_id, href=href, media_type=media_type))

    def add_spine_item(self, idref: str) -> None:
        """Add item to spine."""
        self.spine.append(SpineItem(idref=idref))


@dataclass
class HWPXFile:
    """Complete HWPX file representation.

    HWPX is a ZIP-based format with the following structure:
    - mimetype (uncompressed)
    - version.xml
    - META-INF/container.xml
    - META-INF/manifest.xml
    - Contents/content.hpf
    - Contents/header.xml
    - Contents/section0.xml, section1.xml, ...
    - Contents/MasterPage/masterPage0.xml, ...
    - BinData/... (embedded images, etc.)
    """

    version: VersionXML = field(default_factory=VersionXML)
    container: ContainerXML = field(default_factory=ContainerXML)
    manifest: ManifestXML = field(default_factory=ManifestXML)
    content_hpf: ContentHPF = field(default_factory=ContentHPF)

    # XML content as strings (to be generated by builders)
    header_xml: str = ""
    section_xml_list: List[str] = field(default_factory=list)
    master_page_xml_list: List[str] = field(default_factory=list)
    settings_xml: Optional[str] = None

    # Binary data
    bin_data: Dict[str, bytes] = field(default_factory=dict)

    def add_section_xml(self, section_xml: str) -> None:
        """Add section XML content."""
        self.section_xml_list.append(section_xml)

    def add_master_page_xml(self, master_page_xml: str) -> None:
        """Add master page XML content."""
        self.master_page_xml_list.append(master_page_xml)

    def add_bin_data(self, name: str, data: bytes) -> None:
        """Add binary data (image, etc.)."""
        self.bin_data[name] = data

    @property
    def section_count(self) -> int:
        """Get number of sections."""
        return len(self.section_xml_list)

    @property
    def master_page_count(self) -> int:
        """Get number of master pages."""
        return len(self.master_page_xml_list)
