"""HWP format enumerations."""

from hwp2hwpx.hwp.enums.border_fill import (
    BorderThickness,
    BorderType,
    BorderType2,
    DiagonalType,
    FillType,
    GradientType,
    ImageFillType,
    PatternType,
)
from hwp2hwpx.hwp.enums.char_shape import (
    CharOffsetType,
    EmphasisType,
    FontType,
    OutlineType,
    ScriptType,
    ShadowType,
    StrikeoutType,
    SymbolMarkSort,
    UnderlineType,
)
from hwp2hwpx.hwp.enums.control import (
    ArcType,
    ControlType,
    GsoType,
    HeaderFooterApplyPage,
    HeightCriterion,
    HorzAlign,
    HorzRelTo,
    LineArrowShape,
    LineArrowSize,
    LineEndShape,
    LineType,
    NumberSort,
    ObjectNumberSort,
    TextFlowType,
    TextVerticalAlignment,
    VertAlign,
    VertRelTo,
    WidthCriterion,
)
from hwp2hwpx.hwp.enums.para_shape import (
    Alignment,
    BreakType,
    HeadingType,
    LineSpacingType,
    NumberShape,
    ParagraphNumberFormat,
    TabLeader,
    TabType,
    ValueType,
    VerticalAlignment,
)
from hwp2hwpx.hwp.enums.tags import HWPTag, get_tag_name, is_bodytext_tag, is_docinfo_tag

__all__ = [
    # border_fill
    "BorderThickness",
    "BorderType",
    "BorderType2",
    "DiagonalType",
    "FillType",
    "GradientType",
    "ImageFillType",
    "PatternType",
    # char_shape
    "CharOffsetType",
    "EmphasisType",
    "FontType",
    "OutlineType",
    "ScriptType",
    "ShadowType",
    "StrikeoutType",
    "SymbolMarkSort",
    "UnderlineType",
    # control
    "ArcType",
    "ControlType",
    "GsoType",
    "HeaderFooterApplyPage",
    "HeightCriterion",
    "HorzAlign",
    "HorzRelTo",
    "LineArrowShape",
    "LineArrowSize",
    "LineEndShape",
    "LineType",
    "NumberSort",
    "ObjectNumberSort",
    "TextFlowType",
    "TextVerticalAlignment",
    "VertAlign",
    "VertRelTo",
    "WidthCriterion",
    # para_shape
    "Alignment",
    "BreakType",
    "HeadingType",
    "LineSpacingType",
    "NumberShape",
    "ParagraphNumberFormat",
    "TabLeader",
    "TabType",
    "ValueType",
    "VerticalAlignment",
    # tags
    "HWPTag",
    "get_tag_name",
    "is_bodytext_tag",
    "is_docinfo_tag",
]
